CREATE TABLE ESTUDANTE(
id NUMBER,
nome VARCHAR2(200) NOT NULL,
data_nascimento DATE NOT NULL,
nr_matricula NUMBER(10) UNIQUE NOT NULL,
ativo char(1),
PRIMARY KEY(id)
);

CREATE SEQUENCE SEQ_ESTUDANTE 
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

INSERT INTO ESTUDANTE (ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'Bruno Rodrigues', TO_DATE('31-12-1997', 'dd-mm-yyyy'), '1823471501', 's');

INSERT INTO ESTUDANTE (ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'Brenda Schmmit', TO_DATE('14-02-2001', 'dd-mm-yyyy'), '4264721008', 's');

INSERT INTO ESTUDANTE (ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'Airton Senna', TO_DATE('01-03-1960', 'dd-mm-yyyy'), '7927996509', 's');

INSERT INTO ESTUDANTE (ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'Neymar Jr', TO_DATE('02/05/1992', 'dd-mm-yyyy'), '9708169307', 's');

INSERT INTO ESTUDANTE (ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'Gustavo Kuerten', TO_DATE('10-09-1976', 'dd-mm-yyyy'), '2232394000', 's');

INSERT INTO ESTUDANTE (ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES (SEQ_ESTUDANTE.nextval, 'Marta Vieira da Silva', TO_DATE('19-02-1986', 'dd-mm-yyyy'), '9607323106', 's');

INSERT INTO ESTUDANTE (ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES (SEQ_ESTUDANTE.nextval, 'Mario Carlos', TO_DATE('20/10/1980', 'dd-mm-yyyy'), '9407323308', 's');

INSERT INTO ESTUDANTE (ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES (SEQ_ESTUDANTE.nextval, 'Roberta Cavalcante', TO_DATE('01-01-2000', 'dd-mm-yyyy'), '1452378961', 's');

INSERT INTO ESTUDANTE (ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES (SEQ_ESTUDANTE.nextval, 'Patricia Justos', TO_DATE('05-02-1999', 'dd-mm-yyyy'), '2784569871', 's');

INSERT INTO ESTUDANTE (ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES (SEQ_ESTUDANTE.nextval, 'Mario Sergio Cortella', TO_DATE('14/07/1956', 'dd-mm-yyyy'), '7451234970', 's');

SELECT * FROM ESTUDANTE;


